version: '3.9'

services:
  loadbalancer:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - core-service
      - user-service

  core-service:
    build:
      context: ./core
    expose:
      - "80"

  user-service:
    build:
      context: ./user
    expose:
      - "80"